---
title: "Elsewhere online"
---

Here are some links to my profiles or activity on other websites. I contribute towards open and citizen science resources and enjoy communicating my research to a broad audience.

## Open science and outreach

::: {.online-grid}

::: {.online-card .inaturalist}

### iNaturalist

I contribute observations and taxonomic identifications to the iNaturalist.

[View profile →](https://www.inaturalist.org/people/fvaux)

:::

::: {.online-card .wikipedia}

### Wikipedia

I do some editing on Wikipedia, focusing on sharing scientific knowledge so that it is free and widely accessible.

[View user page →](https://en.wikipedia.org/wiki/User:IcknieldRidgeway)

:::

::: {.online-card .phylopic}

### PhyloPic

I upload illustrations to PhyloPic, which is a free, open database of silhouette images for biological organisms.

[View contributions →](https://www.phylopic.org/contributors/9238892b-6eb7-471b-8bbf-a4092c19a2b4/felix-vaux-silhouettes)

:::

::: {.online-card .bionomia}

### Bionomia

Some of my contributions to natural history collections and other databases are recorded on Bionomia.

[View profile →](https://bionomia.net/0000-0002-2882-7996)

:::

::: {.online-card .bluesky}

### Bluesky

I post sporadically on Bluesky, mainly sharing studies and news related to evolutionary ecology and genomics.

[View profile →](https://bsky.app/profile/felixvaux.bsky.social)

:::

::: {.online-card .youtube}

### YouTube

I occasionally post work-related videos like presentations or methods walkthroughs on YouTube.

[View profile →](https://www.youtube.com/channel/UCbH27wRP1yxhfP_Hs0NQmeQ)

:::

:::


## Selected videos

::: {.online-video}

### DNA extraction walkthrough

::: {.online-video-description}

A walkthrough for extracting genomic DNA from *Durvillaea* and other macroalgae.

:::

<div class="ratio ratio-16x9">
<iframe
  src="https://www.youtube.com/embed/2zzWelD_1Fk"
  title="Kelp DNA extraction walkthrough"
  allowfullscreen>
</iframe>
</div>

:::


::: {.online-video}

### Recorded seminar

::: {.online-video-description}

A recorded seminar presentation from 2019 on my albacore tuna research.

:::

<div class="ratio ratio-16x9">
<iframe
  src="https://www.youtube.com/embed/5Um3wkId3_E"
  title="Albacore tuna seminar"
  allowfullscreen>
</iframe>
</div>

:::